### ISSUE TITLE
xml editing

### ISSUE THREAD

**Issue by badgettrg** [openMetaAnalysis/Sepsis-and-septic-shock-treatment-with-procalcitonin-guided-antibiotics#4]
@hhassouna Look at about line 9 or 10 on the edit you just did, "</bullet>" is missing.

**Comment by hhassouna** [comment]
I corrected that.

Best,
Habiba

On Oct 4, 2015, at 22:24, Robert Badgett <notifications@github.com<mailto:notifications@github.com>> wrote:

@hhassounahttps://github.com/hhassouna Look at about line 9 or 10 on the edit you just did, "" is missing.
